### ISSUE TITLE
if possible support this feature ?

### ISSUE THREAD

**Issue by jasoncheng** [papandreou/express-hijackresponse#3]
Thanks for this wonderful module, very useful, love this.
all my res.render request can be hjack.

Some routes i used for API (response json data only), i wanna cache all JSON data using your hijack module to do this. 

But not matter what i try, res.json or res.jsonp or res.send, those method can't be hijack.

**Comment by gustavnikolaj** [comment]
Hi @jasoncheng. Sorry for the late reply. I'm afraid I do not entirely understand your problem. If it is at all relevant anymore, I'd be happy to answer, if you could elaborate a bit. Just reopen this issue and explain a bit more what you are trying to achieve.

**Comment by papandreou** [comment]
It sounds more like a problem that could be addressed with memoization in the middleware that generates the response.

You could take a look at https://github.com/papandreou/node-memoizesync or https://github.com/papandreou/node-memoizeasync, depending on whether the code building your response data is sync or async. There are other alternatives, of course :)
