### ISSUE TITLE
Unhijack and wipe response

### ISSUE THREAD

**Issue by olysyuk** [papandreou/express-hijackresponse#7]
I'm trying to cover following use case:

1) Make request to first proxy, 
2) hijack response, and check the result (if it's 404).
3) in case of 404, wipe response body, and headers, and everything and make a call to another proxy

I can not do step 3, because
a. I leave response hijacked (next proxy middleware can not work with it, all data is mocked, unhijack callback inaccessible)
b. I unhijack response (headers are sent and no modification can be done)

Sample code:

```
   var httpProxy = require('http-proxy');
   firstProxy = httpProxy.createServer({target:'http://proxy1'});
   secondProxy = httpProxy.createServer({target:'http://proxy2});

   firstMiddleware = function(req, res, next) { 

        res.hijack(function(err, res) {
            if (res.statusCode === 404) {
                  // res.unhijack(); 
                  // a. Is accessible only here
                  // b. Cause 'headers sent'
                  next();
            } else {
                  res.unhijack();
            } 
        }

        firstProxy.server.web(req, res);
   };


   secondMiddleware = function(req, res, next) {
        secondProxy.server.web(req, res);
        // a. res is hijacked, no output is processed, no way to unhijack it
        // b. 'headers sent'
   } 
```

**Comment by gustavnikolaj** [comment]
Hi @olysyuk,

Sorry for the late reply. I figure that you've found a solution now, but I'm going to add a response anyway.

I totally see what you're trying to do, but hijackresponse it not really the tool for that job. You already handed off the request stream to the first proxy, so you would need to buffer up any request bodies as well. I don't see a way around that, that doesn't place you in a world of hurt.

Instead, I'd suggest writing a little client around a module like request, or teepee, that could handle your failover scenarios... Something along the lines of:

```js
function HttpClientWithFailover(opts) {
    this.urls = opts.urls
}

HttpClientWithFailover.prototype.get = function (params, cb) {
    this._get(params, 0, cb)
}

HttpClientWithFailover.prototype._get = function (params, i, cb) {
    var requestOpts = { method: 'GET', url: this.urls[i] }
    // extend requestOpts with params
    request(requestOpts, function (err, response, body) {
        if (err || response.statusCode !== 200) {
            i = i + 1
            if (i < this.urls.length) {
                if (!err) {
                    err = new Error('Expected statusCode 200, but got ' + response.statusCode)
                }
                return cb(err)
            }
            return this._get(params, i, cb);
        }
        return cb(null, body)
    }.bind(this))
}
```

Then using that in your middleware like this:

```js
var proxyClient = new HttpClientWithFailover({
    urls: ['http://proxy1', 'http://proxy2' ]
})

express
    .use(function (req, res, next) {
        proxyClient({ path: '/foo' }, function (err, body) {
            if (err) return next(err)
            res.end(body)
        })
    })
```

While the code above will not work, I hope it is enough to explain the idea.
